name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
  BRANCH: ${{ github.event_name == 'pull_request' && format('refs/heads/{0}', github.event.pull_request.head.ref) || github.ref }}

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]
        os: ["ubuntu-latest"]

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ${{ matrix.os }}

    steps:
      - name: Prepare repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 0

      - name: Set up Node v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Build Monorepo
        run: npm run build
