# Workflow for testing a Storybook instance

name: "Storybook Tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install playwright dependency [1/3]
        run: npm -g i playwright

      - name: Install playwright dependency [2/3]
        run: pnpm i playwright -w

      - name: Install playwright dependency [3/3]
        run: pnpm exec playwright install

      - name: Test Component Library
        run: pnpm run storybook-test
